# Generated by Django 5.2 on 2025-04-25 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_note_updated_at_note_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='category',
            field=models.CharField(choices=[('Important', 'Important'), ('Tasks', 'Tasks'), ('Study', 'Study'), ('Personal', 'Personal'), ('Archive', 'Archive'), ('All', 'All')], default='All', max_length=20),
        ),
    ]
