# Generated by Django 5.2 on 2025-05-12 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_profile_dark_mode_profile_notifications_enabled_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='dark_mode',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='notifications_enabled',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='public_profile',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='show_activity',
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='profile_images/default.png', upload_to='profile_images/'),
        ),
    ]
